image: scrapinghub

script:
  - |
    # SSH is needed to run test
    BASEI=i.scrapinghub.com/crawlera/docker-erlang-otp/elixir/otp23:7a265a2-slim
    build_docker_image \
      --build-arg BASE_IMAGE=$BASEI\
      --build-arg DISABLE_SYSLOG=1 \
      --build-arg DISABLE_SSH=0 \
      --rm image
  - |
    set -ex
    NAME=${APPIMAGE/:*/} \
    VERSION=${APPIMAGE/*:/} \
    make test
  - push_docker_image

