image: scrapinghub

script:
  - build_docker_image --build-arg BASE_IMAGE=elixir:1.9.1-slim --build-arg DISABLE_SYSLOG=1 --build-arg=DISABLE_SSH=0 --rm image  # SSH is needed to run test
  - |
    set -ex
    NAME=${APPIMAGE/:*/} \
    VERSION=${APPIMAGE/*:/} \
    make test
  - push_docker_image

